server:
  port: 8071

spring:
  application:
    name: ccpdemo-service

axon:
  kafka:
    clientid: saga-service
    defaulttopic: saga.aggregator.event
    consumer:
      group-id: "local.event.consumer-group"
      bootstrapservers: localhost:9092

    properties:
      security.protocol: PLAINTEXT