server:
  port: 6060

spring:
  application:
    name: entdemo-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


axon:
  eventhandling:
    processors:
      "[MyProcessor]":
        source: kafkaMessageSource
        mode: TRACKING
  kafka:
    default-topic: aggqueue1
    producer:
      bootstrap-servers:
        - localhost:9092
      transaction-id-prefix: clxtrx1
    consumer:
      group-id: ent
      bootstrapservers:
        - localhost:9092

